intents:
  - name: "general"
    description: "General conversation and Q&A"
  - name: "code"
    description: "Programming and code generation"
  - name: "translation"
    description: "Text translation between languages"
  - name: "creative writing"
    description: "Creative writing and content generation"
  - name: "math"
    description: "Mathematical problem solving and reasoning"

models:
  - name: "llama2"
    model_name: "llama-2-7b-chat"
    endpoint: "http://localhost:1234/v1/chat/completions"
    supported_intents: ["general", "translation", "creative writing"]
    supported_languages: ["en", "es", "fr", "ru", "de", "he", "zh"]
    weight: 1.0
    enabled: true
    context_length: 4096

  - name: "qwen_coder"
    model_name: "Qwen2.5-Coder-7B-Instruct" 
    endpoint: "http://localhost:1234/v1/chat/completions"
    supported_intents: ["code"]
    supported_languages: ["en", "ru", "he", "fr", "de", "es", "zh"]
    weight: 1.2
    enabled: true
    context_length: 32768

  - name: "wizardmath"
    model_name: "WizardMath-7B-V1.1-GGUF"
    endpoint: "http://localhost:1234/v1/chat/completions"
    supported_intents: ["math"]
    supported_languages: ["en", "ru", "he"]
    weight: 1.3
    enabled: true
    context_length: 4096


rules:
  - intent: "general"
    model: "llama2"
  - intent: "math"
    language: "en"
    model: "llama2"
  - intent: "code"
    language: "en"
    model: "qwen_coder"

intent_classifier:
  template: |
    Analyze the user's message and classify it into one of these intents:
    - "code": Requests related to programming, algorithms, or code examples
    - "math": Requests involving mathematical calculations or problems
    - "translation": Requests to translate text from one language to another
    - "creative writing": Requests to write stories, emails, poems, or other creative content
    - "general": All other requests
    
    Examples:
    User: "Write a Python function to reverse a string" → "code"
    User: "How to calculate factorial in Python" → "code"
    User: "What's the square root of 144?" → "math"
    User: "Tell me about the history of computers" → "general"
    User: "Translate 'Hello' to French" → "translation"
    User: "Translate this sentence to Spanish: 'How are you?'" → "translation"
    User: "Write a story about a brave knight" → "creative writing"
    User: "Compose an email to my boss about a meeting" → "creative writing"
    User: "Write a poem about the sea" → "creative writing"
    
    Respond with only the intent label ("code", "math", "translate", "creative writing", or "general").

system_templates:
  markdown_response: |
    You are a helpful assistant. Always format your responses in valid Markdown.
    - For code, use triple backticks and specify the language (e.g., ```python).
    - Explanations should be in plain text or markdown.
    - Never return code as a single line; always preserve the original line breaks and indentation.
    - Example:
        ```python
        def hello():
            print("Hello, world!")
        ```
  code: |
    You are a coding assistant. Always format your responses in valid Markdown.
    - For code, use triple backticks and specify the language (e.g., ```python).
    - Explanations should be in plain text or markdown.
    - Never return code as a single line; always preserve the original line breaks and indentation.
    - Example:
        ```python
        def hello():
            print("Hello, world!")
        ```
  math: |
    You are a math assistant. Format all equations and math explanations in Markdown, using LaTeX where appropriate. For calculations, show all steps clearly.
    - Example:
        The quadratic formula is $x = \frac{-b \pm \sqrt{b^2-4ac}}{2a}$
  translation: |
    You are a translation assistant. Respond with only the translated text, formatted in Markdown. If the user requests multiple languages, clearly separate each translation.
    - Example:
        **French:** Bonjour
        **Spanish:** Hola
  creative_writing: |
    You are a creative writing assistant. Format stories, poems, emails, and other creative content in Markdown. Use headings, lists, and formatting to make the output engaging and readable.
    - Example:
        # A Poem About the Sea
        The waves crash gently on the shore...
  general: |
    You are a helpful assistant. Format all responses in Markdown. Use lists, headings, and formatting to make information clear and easy to read. For factual answers, cite sources if possible.
    - Example:
        ## The History of Computers
        Computers have evolved rapidly since the 20th century...

